

base_dir: "/home/jturner/VIIRS_to_AWIPS/awips_example_data/"
viirs_pattern: "/mnt/viirs/WI-CONUS/NPP/SDR-MBand/2025/04/22/SVM16_npp_d20250422_t07*"

p2g_source: '/local/polar2grid_v_3_1/bin/polar2grid.sh'
reader_name: 'viirs_sdr'
writer_name: 'awips_tiled'
products_list: 'm16'
grid_name: 'us_viirs2awips_m'
sector_id: 'LCC'
grid_configs: '/home/jturner/VIIRS_to_AWIPS/custom_grids.conf'