

base_dir: "/home/jturner/VIIRS_to_AWIPS/"
viirs_pattern: "/mnt/viirs/WI-CONUS/NPP/SDR-MBand/2025/03/25/?????_npp_d20250325_t2206*"

p2g_source: '/local/polar2grid_v_3_1/bin/polar2grid.sh'
reader_name: 'viirs_sdr'
writer_name: 'awips_tiled'
products_list: 'm08'